#!/bin/bash

RANCHEROS_VERSION="v0.3.1"
RANCHEROS_IMAGE=RancherOS-${RANCHEROS_VERSION}-2-post1

BUILD_USER_PUB=${BUILD_USER_PUB:-./vagrant.pub}
BUILD_USER_KEY=${BUILD_USER_KEY:-./vagrant}

chmod 0600 ${BUILD_USER_KEY}
chmod 0600 ${BUILD_USER_PUB}
